turbopy:
  image: reutersmedia/turboparser:latest
  mem_limit: 6000000000 
  cpu_shares: 128
  restart: always
  ports:
    - "8080:80"
  links:
    - "semafor-frameparser:frameparser"
  volumes_from:
    - turboparser-models:ro
  environment:
    ENVIRONMENT: dev
    APPLICATION: turboparser
    NUM_PYTHON_PROCESSES: 1
    NUM_UWSGI_THREADS: 1
    FRAMEPARSER_HOST: frameparser
    FRAMEPARSER_PORT: 8085
    LOG_LEVEL: INFO
turboparser-models:
  image: reutersmedia/turboparser-models:latest
semafor-frameparser:
  image: reutersmedia/semafor-frameparser:latest
  mem_limit: 4400000000
  cpu_shares: 128
  expose:
    - "8085"
  
